config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pictures

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
  registrations: "users/registrations",
  omniauth_callbacks: "users/omniauth_callbacks"
  }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
         can :access, :rails_admin   # grant access to rails_admin
         can :manage, :all
      end
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pictures
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader


  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
       user = User.new(
         name:     auth.extra.raw_info.name,
         provider: auth.provider,
         uid:      auth.uid,
         email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
         image_url:   auth.info.image,
         password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save(validate: false)
    end
   user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
  user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name:     auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
   user
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

# before_actionで下で定義したメソッドを実行
before_action :configure_permitted_parameters, if: :devise_controller?

#変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

protected

  #deviseのストロングパラメーターにカラム追加するメソッドを定義
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
    devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.create(pictures_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path,  notice: "写真を投稿しました！"
    NoticeMailer.sendmail_picture(@picture).deliver
    else
      render 'new'
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end


  def update
    @picture = Picture.find(params[:id])
    @picture.update(pictures_params)
    if @picture.save
      redirect_to pictures_path,　notice: "写真を更新しました！"
    else
      render 'edit'
    end
  end

  def show
   @picture = Picture.find(params[:id])
  end


  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path, notice: "写真を削除しました"
  end


  private
    def pictures_params
      params.require(:picture).permit(:image, :content)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end
  end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
      image_tag(img_url, alt: user.name)
  end
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit(id)
    if action_name == 'new'
      pictures_path
    elsif action_name == 'edit'
      picture_path(id)
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="left li">
      <li><%= link_to 'ホーム', root_path %></li>
      <li><%= link_to 'お知らせ', "#" %></li>
    </div>
    <div class="right li">
      <li><%= link_to '投稿一覧', pictures_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'マイページ', edit_user_registration_path %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path  %></li>
      <li><%= link_to '新規会員登録', new_user_registration_path %></li>
    <% end %>
    </div>
  </header>
<section class="post">

<%= yield %>
</section>
  <footer>
  </footer>
  </body>
</div>
</html>

app/views/pictures/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@picture, url: choose_new_or_edit(@picture.id)) do |f| %>

<%= f.error_messages! %>

 <%= f.label :image %>
 <%= f.file_field :image, class: 'form-control' %>
 <%= f.hidden_field :image_cache %>
 <br>
 <%= f.label :content %>
 <%= f.text_field :content, class: 'form-control'  %>
 <br>
 <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>


<%= link_to "投稿一覧画面に戻る", pictures_path %>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>投稿写真一覧</h1>
      <%= link_to "写真を投稿する", new_picture_path, class: 'btn btn-default' %>
      
    <% @pictures.each do |picture| %>
    <!--<div class="row">-->
    <div class="profileimg"><%= profile_img(picture.user) %></div>
      <div class="postimg">
      <strong><%= image_tag picture.image %></strong>
      </div>
      <p><%= picture.content %></p>
      <%= link_to "投稿詳細へ移る", picture_path(picture.id), class: 'btn btn-default btn-sm btn-info' %>
      <%= link_to "投稿写真を編集する", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "投稿写真を削除する", picture_path(picture.id), method: :delete, class: 'btn btn-default btn-sm btn btn-danger' %>
     <% end %>
    <!--</div>-->
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
  <div class="imagedetail">
    <strong>◆投稿写真</strong>
    <%= image_tag @picture.image %>
  </div>
  <div class="postdetail">
    <strong>◆投稿内容:</strong>
    <%= @picture.content %>

    <br>
    <%= link_to '一覧へ戻る', pictures_path %>
  </div>

app/views/top/index.html.erb
<p class="flash"><%= notice %><%= alert %></p>

  <div class="topicon">
    <%= image_tag "top_image.jpg" %>
  </div>